### ISSUE TITLE
Testdata_R1.tiny.fastq.gz no longer available

### ISSUE THREAD

**Issue by tgbrooks** [nf-core/testpipeline#46]
The file: https://github.com/nf-core/test-datasets/raw/exoseq/testdata/Testdata_R1.tiny.fastq.gz is now a 404. This causes the test pipeline to crash.

**Comment by mashehu** [comment]
Sorry that I didn't see this issue earlier. This is just a repository to test certain nf-core features. The exoseq pipeline has never been released and is archived.
